version: '3.8'

services:
  api-gateway:
    build:
      context: .
      dockerfile: apps/api-v2/services/api-gateway/Dockerfile
    ports:
      - "3333:3333"  # External access
    env_file:
      - .env
    hostname: api-gateway
    container_name: api-gateway
    networks:
      - app-network
    depends_on:
      - analytics-service
      - auth-service
      - billing-service
      - components-service
      - execution-service
      - projects-service
      - users-service
      - workflows-service
    restart: always
    volumes:
      - ./apps/api-v2/services/api-gateway:/app/apps/api-v2/services/api-gateway
      - ./packages:/app/packages
      - ./apps/api-v2/libs:/app/apps/api-v2/libs

  analytics-service:
    build:
      context: .
      dockerfile: apps/api-v2/services/analytics-service/Dockerfile
    expose:
      - "3347"  # Expose port for internal network communication
    hostname: analytics-service
    container_name: analytics-service
    env_file:
      - .env
    networks:
      - app-network
    restart: always
    volumes:
      - ./apps/api-v2/services/analytics-service:/app/apps/api-v2/services/analytics-service
      - ./packages:/app/packages
      - ./apps/api-v2/libs:/app/apps/api-v2/libs

  auth-service:
    build:
      context: .
      dockerfile: apps/api-v2/services/auth-service/Dockerfile
    expose:
      - "3340"  # Expose port for internal network communication
    hostname: auth-service
    container_name: auth-service
    env_file:
      - .env
    networks:
      - app-network
    restart: always
    volumes:
      - ./apps/api-v2/services/auth-service:/app/apps/api-v2/services/auth-service
      - ./packages:/app/packages
      - ./apps/api-v2/libs:/app/apps/api-v2/libs

  billing-service:
    build:
      context: .
      dockerfile: apps/api-v2/services/billing-service/Dockerfile
    expose:
      - "3344"  # Expose port for internal network communication
    hostname: billing-service
    container_name: billing-service
    env_file:
      - .env
    networks:
      - app-network
    restart: always
    volumes:
      - ./apps/api-v2/services/billing-service:/app/apps/api-v2/services/billing-service
      - ./packages:/app/packages
      - ./apps/api-v2/libs:/app/apps/api-v2/libs

  components-service:
    build:
      context: .
      dockerfile: apps/api-v2/services/components-service/Dockerfile
    ports:
      - "3348:3348" # External access
    expose:
      - "3345"  # Expose port for internal network communication
      - "3348"  # Expose port for external network communication
    hostname: components-service
    container_name: components-service
    env_file:
      - .env
    networks:
      - app-network
    restart: always
    volumes:
      - ./apps/api-v2/services/components-service:/app/apps/api-v2/services/components-service
      - ./packages:/app/packages
      - ./apps/api-v2/libs:/app/apps/api-v2/libs

  execution-service:
    build:
      context: .
      dockerfile: apps/api-v2/services/execution-service/Dockerfile
    expose:
      - "3343"  # Expose port for internal network communication
    hostname: execution-service
    container_name: execution-service
    env_file:
      - .env
    networks:
      - app-network
    restart: always
    volumes:
      - ./apps/api-v2/services/execution-service:/app/apps/api-v2/services/execution-service
      - ./packages:/app/packages
      - ./apps/api-v2/libs:/app/apps/api-v2/libs

  projects-service:
    build:
      context: .
      dockerfile: apps/api-v2/services/projects-service/Dockerfile
    expose:
      - "3346"  # Expose port for internal network communication
    hostname: projects-service
    container_name: projects-service
    env_file:
      - .env
    networks:
      - app-network
    restart: always
    volumes:
      - ./apps/api-v2/services/projects-service:/app/apps/api-v2/services/projects-service
      - ./packages:/app/packages
      - ./apps/api-v2/libs:/app/apps/api-v2/libs

  users-service:
    build:
      context: .
      dockerfile: apps/api-v2/services/users-service/Dockerfile
    expose:
      - "3341"  # Expose port for internal network communication
    hostname: users-service
    container_name: users-service
    env_file:
      - .env
    networks:
      - app-network
    restart: always
    volumes:
      - ./apps/api-v2/services/users-service:/app/apps/api-v2/services/users-service
      - ./packages:/app/packages
      - ./apps/api-v2/libs:/app/apps/api-v2/libs

  workflows-service:
    build:
      context: .
      dockerfile: apps/api-v2/services/workflows-service/Dockerfile
    hostname: workflows-service
    container_name: workflows-service
    env_file:
      - .env
    networks:
      - app-network
    restart: always
    volumes:
      - ./apps/api-v2/services/workflows-service:/app/apps/api-v2/services/workflows-service
      - ./packages:/app/packages
      - ./apps/api-v2/libs:/app/apps/api-v2/libs

networks:
  app-network:
    name: app-network
    driver: bridge