version: '3.8'

services:
  api-gateway:
    build:
      context: .
      dockerfile: apps/api-v2/services/api-gateway/Dockerfile
    ports:
      - "3333:3333"  # External access
    env_file:
      - .env
    hostname: api-gateway
    networks:
      - app-network
    depends_on:
      - analytics-service
      - auth-service
      - billing-service
      - components-service
      - execution-service
      - projects-service
      - users-service
      - workflows-service
    restart: always

  analytics-service:
    build:
      context: .
      dockerfile: apps/api-v2/services/analytics-service/Dockerfile
    expose:
      - "3347"  # Expose port for internal network communication
    hostname: analytics-service
    env_file:
      - .env
    networks:
      - app-network
    restart: always

  auth-service:
    build:
      context: .
      dockerfile: apps/api-v2/services/auth-service/Dockerfile
    expose:
      - "3346"  # Expose port for internal network communication
    hostname: auth-service
    env_file:
      - .env
    networks:
      - app-network
    restart: always

  billing-service:
    build:
      context: .
      dockerfile: apps/api-v2/services/billing-service/Dockerfile
    expose:
      - "3345"  # Expose port for internal network communication
    hostname: billing-service
    env_file:
      - .env
    networks:
      - app-network
    restart: always

  components-service:
    build:
      context: .
      dockerfile: apps/api-v2/services/components-service/Dockerfile
    ports:
      - "3348:3348" # External access
    expose:
      - "3344"  # Expose port for internal network communication
    hostname: components-service
    env_file:
      - .env
    networks:
      - app-network
    restart: always

  execution-service:
    build:
      context: .
      dockerfile: apps/api-v2/services/execution-service/Dockerfile
    expose:
      - "3343"  # Expose port for internal network communication
    hostname: execution-service
    env_file:
      - .env
    networks:
      - app-network
    restart: always

  projects-service:
    build:
      context: .
      dockerfile: apps/api-v2/services/projects-service/Dockerfile
    expose:
      - "3342"  # Expose port for internal network communication
    hostname: projects-service
    env_file:
      - .env
    networks:
      - app-network
    restart: always

  users-service:
    build:
      context: .
      dockerfile: apps/api-v2/services/users-service/Dockerfile
    expose:
      - "3341"  # Expose port for internal network communication
    hostname: users-service
    env_file:
      - .env
    networks:
      - app-network
    restart: always

  workflows-service:
    build:
      context: .
      dockerfile: apps/api-v2/services/workflows-service/Dockerfile
    expose:
      - "3340"  # Expose port for internal network communication
    hostname: workflows-service
    env_file:
      - .env
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge