global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    metrics_path: '/api/metrics'
    static_configs:
      - targets: [ 'api-gateway:3333' ]
    scrape_interval: 15s