name: Deploy backend to VPS using Turbo

on:
  push:
    branches: # Only deploy on push to main branch
      - main
  workflow_dispatch:  # Allow manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add VPS to known hosts
        run: |
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        run: |
          ssh ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} "\
            cd ${{ secrets.DEPLOY_PATH }} && \
            git fetch origin main && \
            git reset --hard origin/main && \
            pnpm install && \
            pnpm run build:backend && \
            pnpm run start:backend \
          "